# Central tuning knobs for waits/retries/thresholds.

PREPARE_SCROLL_WAIT_MS = 350
EXPAND_TEXT_WAIT_MS = 250
HIGHLIGHT_RETRY_WAIT_MS = 200
HIGHLIGHT_SCROLL_WAIT_MS = 250
VISUAL_SETTLE_WAIT_MS = 200
MULTIPART_STEP_WAIT_MS = 180
REHIGHLIGHT_WAIT_MS = 120
LONG_TEXT_EXPAND_SETTLE_MS = 160
